name: Recompile blocklist and allowlist from sources

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Needed to push commits back to the repo

jobs:
  recompile:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Download OISD Big List
        run: |
          curl -L https://big.oisd.nl/ -o ../oisd.txt

      - name: Compile Blocklist
        run: |
          npx @adguard/hostlist-compiler -v -c hostlist-compiler-config.json -o blocklist

      - name: Post-process Blocklist
        run: |
          # Capture whitelisted entries to allowlist
          grep '^@@' blocklist > allowlist || true
          # Remove all whitelisted entries
          sed -i '/^@@/d' blocklist
          # Remove empty lines
          sed -i '/^$/d' blocklist

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blocklist allowlist
          if git diff --cached --quiet; then
            echo "No changes in blocklist and allowlist."
          else
            currentDate=$(date '+%Y-%m-%d')
            currentTime=$(date '+%H:%M:%S')
            git commit -m "Auto-regenerated blocklist and allowlist ${currentDate} ${currentTime}"
            git pull --rebase -X ours origin master
            git push
          fi
